### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by xdeng7** [CircleRadon/Osprey#1]
Hi, very nice work, do you have any specific plan to release the data?

**Comment by CircleRadon** [comment]
Hi, @xdeng7 
Thanks for your interest in our work! The data will be released expect in the coming 1-2 weeks. Please stay tuned!

**Comment by addalaaditya** [comment]
Please 🙏 release as soon as possible

**Comment by CircleRadon** [comment]
Hi, @xdeng7 @addalaaditya, our data and training code have been released.

**Comment by xdeng7** [comment]
Thank you for letting me know.

Xueqing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
