### ISSUE TITLE
checkpoint/osprey_7b 

### ISSUE THREAD

**Issue by YuWeigang** [CircleRadon/Osprey#10]
I have placed all the files from https://huggingface.co/sunshine-lwt/Osprey-7b/tree/main into the Osprey-main/checkpoint/osprey_7b folder, but an error occurred.
OSError: We could not connect to 'https://huggingface.co/' to load this file, it is also not found in the cache files, and it appears that checkpoint/osprey_7b is not a path to a directory containing a file named config.json. Please check your internet connection, or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

"I have also placed the open_clip_pytorch_model.bin file in the Osprey-main/checkpoint/osprey_7b folder. Additionally, the 'mm_vision_tower' is set to 'checkpoint/osprey_7b/open_clip_pytorch_model.bin', and the sam_vit_b_01ec64.pth file has been placed in the Osprey-main/checkpoints folder."

**Comment by CircleRadon** [comment]
Hello, @YuWeigang. 
The default path for osprey_7b is in `demo/checkpoint`, because the path to run the script is in the `demo`, so the default path of all the checkpoints should be:
```
├── demo
    ├── checkpoint
    │   └── osprey_7b
    ├── checkpoints
    │   └──sam_vit_b_01ec64.pth 
    └──open_clip_pytorch_model.bin
```
Current path setting may cause a confusion for reader, we will polish this to make it more clear.

**Comment by YuWeigang** [comment]
"Your README and comments are inconsistent. Also, it seems that the weight file might be corrupted on my end. I am planning to redownload it. RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory."
