### ISSUE TITLE
The checkpoint-final of stage2

### ISSUE THREAD

**Issue by xin-ran-w** [CircleRadon/Osprey#14]
Hello, I was wondering if you could kindly assist me with my request. I am interested in starting my training journey from stage 3, and I was wondering if it would be possible for you to provide me with the checkpoint of stage 2?

**Comment by CircleRadon** [comment]
Hi, @xin-ran-w 
We have uploaded the stage2 weights on [https://huggingface.co/sunshine-lwt/Osprey-7b-stage2](https://huggingface.co/sunshine-lwt/Osprey-7b-stage2/tree/main), please feel free to have a try.

**Comment by xin-ran-w** [comment]
Thank you！😀
