### ISSUE TITLE
Addign Open Vocabulary Segmentation to Demo

### ISSUE THREAD

**Issue by joshmyersdean** [CircleRadon/Osprey#17]
Hello!

Thank you for this great work! I was wondering if there is any easy way to extend the demo to include open-vocab segmentation?

Thank you!
Josh

**Comment by LiWentomng** [comment]
@joshmyersdean  Hello, thanks again. 
Our model aims to understand the mask-level region, including semantic categroy and short/long description, instead of directly outputing masks.

**Comment by joshmyersdean** [comment]
Thank you!
