### ISSUE TITLE
Mask-level Ferret?

### ISSUE THREAD

**Issue by joshmyersdean** [CircleRadon/Osprey#18]
Hello again!

I was wondering how you were able to have Ferret output segmentation masks? From the paper it looks like it is restricted to yo bounding boxes?

Thank you!

**Comment by LiWentomng** [comment]
@joshmyersdean Hello,  thanks for your interests.
All models only generate the semantic understanding, not outputing segmentation masks. Regarding open-vocabulary segmentation, all models use the groundth-truth of mask to conduct the performance evaluation of their semantic interpretation capabilities.

**Comment by joshmyersdean** [comment]
Thank you!
