### ISSUE TITLE
Can not load the page for the online demo

### ISSUE THREAD

**Issue by xdeng7** [CircleRadon/Osprey#19]
Even enter the password and name for the online demo, the demo page is not loading. Could you please take a look to fix it?

**Comment by xdeng7** [comment]
> @xdeng7 Hello, we have tested the demo and it is working as expected. It's possible that network issues may be affecting your experience. Please check your network, and try again.

thanks for the confirmation. now it is working, I guess it is because of the network issues for ip address in united states?

**Comment by LiWentomng** [comment]
@xdeng7  
Yes, the network response latency of foreign ip nodes is likely to be higher.
