### ISSUE TITLE
Can you tell me the computer configuration requirements for this?

### ISSUE THREAD

**Issue by cloudmisst** [CircleRadon/Osprey#2]
Can you tell me the computer configuration requirements for this?

**Comment by CircleRadon** [comment]
Hi, @cloudmisst. For inference, it needs about 17GB GPU memory for Osprey(15GB) and SAM(2GB).

**Comment by cloudmisst** [comment]
> Hi, @cloudmisst. For inference, it needs about 17GB GPU memory for Osprey(15GB) and SAM(2GB).

Thank you
