### ISSUE TITLE
can not access your dataset

### ISSUE THREAD

**Issue by alexwangmac** [CircleRadon/Osprey#21]
Hi, thank you for your awesome work. However, I am unable to access the dataset mentioned in your data preparation section as the link provided is unavailable. Could you please provide an updated link? Thank you!

Incorrect link:
pascal_part: [train.json](https://huggingface.co/datasets/sunshine-lwt/Osprey-TrainingData/resolve/main/pascalpart_train.json?download=true), [VOCdevkit](http://host.robots.ox.ac.uk/pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar).

**Comment by LiWentomng** [comment]
@alexwangmac  
Hello, thank you for your interest.

The link to train.json is active and should work as expected. For the VOCdevkit, you can download it directly from the [official page](http://host.robots.ox.ac.uk/pascal/VOC/voc2010/#data), and then select `Download the training/validation data` to begin the download.

**Comment by alexwangmac** [comment]
Thank you! I have successfully downloaded the dataset.
