### ISSUE TITLE
How to use Osprey in my own dataset

### ISSUE THREAD

**Issue by joy91269** [CircleRadon/Osprey#22]
Thank you for your amazing work. And here is the thing, what should i do to link your Osprey with my own dataset? I have some images collected by our team. Should i retrain the model to make the description of every area more accurate? how to do this? And because it is a folder of images not just one image that i can use in the demo. How to use your model in a large amount of images and collect all the result?

**Comment by CircleRadon** [comment]
Hello, @joy91269 
If you find that the generated description of our model is not so accurate for your domain data, you can consider finetuning the model with your own dataset.  To do this, ensure your data is formatted in accordance with the osprey-724k dataset we've provided.

When you wish to conduct inference on a collection of images, you'll need to run the demo code on your local machine. Additionally, you should craft a script that processes each image, feeding the each mask region into the model to obtain the corresponding answers.

**Comment by joy91269** [comment]
I send you a email to your @zju.edu.com to ask more detail things.
