### ISSUE TITLE
about the training log

### ISSUE THREAD

**Issue by chencn2020** [CircleRadon/Osprey#27]
你好，我最近想尝试在自己的数据集上训练模型
但不是很清楚三个stage训练的损失收敛到多少才算训练完成

请问能不能提供一下三个stage的训练log，或者告知一下三个stage收敛后loss大致的范围

感谢🙏

**Comment by CircleRadon** [comment]
你好，loss的范围大概是这样：
stage1训练完loss大概是3左右，
stage2在1-2之间，训练完可以输出一些简单的类别
stage3大概是0.8左右
不同的数据情况也不太一样，可以做个参考
