### ISSUE TITLE
Output mask features.

### ISSUE THREAD

**Issue by jkli1998** [CircleRadon/Osprey#35]
Thanks for sharing this impressive work :)

I notice that osprey shows the ability of outputing mask features in the conversation. (Figure 2 in the original paper, Conversations and Complex Reasoning). Dynamically changing the classification head of a large language model based on mask features and predicting them sounds very difficult. I would like to know how osprey achieves to output mask categories?

Looking forward to your reply.

**Comment by LiWentomng** [comment]
@jkli1998 
Hello, in Osprey, mask features can be projected as the mask tokens in text space. These mask tokens are then interleaved with image/text tokens to feed the llm and generate accurate semantic understanding. This process is trained with region-based instruction data to fully utilize the ability of the llm.

**Comment by korcys** [comment]
> @jkli1998 Hello, in Osprey, mask features can be projected as the mask tokens in text space. These mask tokens are then interleaved with image/text tokens to feed the llm and generate accurate semantic understanding. This process is trained with region-based instruction tuning data to fully utilize the ability of the llm.

Thanks for your kind reply. 
Mask features can indeed be used as the inputs to llm. But I found that Figure 2 shows the mask features as the `outputs` of llm, e.g. the `<region5>` in the answer. I would like to know how to `output` these mask features.

**Comment by jkli1998** [comment]
> @jkli1998 Hello, in Osprey, mask features can be projected as the mask tokens in text space. These mask tokens are then interleaved with image/text tokens to feed the llm and generate accurate semantic understanding. This process is trained with region-based instruction tuning data to fully utilize the ability of the llm.

Thanks for your kind reply. 
Mask features can indeed be used as the inputs to llm. But I found that Figure 2 shows the mask features as the `outputs` of llm, e.g. the `<region5>` in the answer. I would like to know how to `output` these mask features.

**Comment by LiWentomng** [comment]
@jkli1998 
Sorry for the misunderstanding regarding Figure 2. The output <region> is for illustration only. The model does not output mask features.

**Comment by jkli1998** [comment]
I got it. Thanks.
