### ISSUE TITLE
Download issue for ospery model checkpoint

### ISSUE THREAD

**Issue by PerfectBlueFeynman** [CircleRadon/Osprey#8]
Hi, first, thank you for the amazing work!

I'm wondering if you provide a google drive to your model checkpoint or some other downloadable link? I tried to download it from huggingface model repo, but either I got an error saying osprey is not a valid key or access was denied in the git command.

Is there another way to download the checkpoint model so that I can try to deploy it locally?

Thank you

**Comment by LiWentomng** [comment]
@PerfectBlueFeynman 
Hello! Unfortunately, our Google Drive storage has reached its capacity limit and is not avaliable to accommodate the entire model. 

You can directly download the model files one by one from the Hugging Face website.

Additionally, I've tested the following git commands successfully for cloning the repository:
`git lfs install`
`git clone https://huggingface.co/sunshine-lwt/Osprey-7b`

Should you encounter any issues, feel free to share the error log here, and we'll be happy to assist you.
